<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);
include 'db.php';

echo "<h2>تحديث قاعدة البيانات...</h2>";

// 1. Add Image Column
$sql_alter = "ALTER TABLE products ADD image VARCHAR2(255)";
$stmt = oci_parse($conn, $sql_alter);

// Try to execute ALTER. If it fails, check if it's because column exists
if (@oci_execute($stmt)) {
    echo "✅ تم إضافة عمود الصور بنجاح.<br>";
} else {
    $e = oci_error($stmt);
    // ORA-01430: column being added already exists in table
    if ($e['code'] == 1430) {
        echo "ℹ️ عمود الصور موجود مسبقاً.<br>";
    } else {
        echo "❌ خطأ في إضافة العمود: " . $e['message'] . "<br>";
    }
}

// 1.5 Add Phone Column to Users
$sql_alter_phone = "ALTER TABLE users ADD phone VARCHAR2(20)";
$stmt_phone = oci_parse($conn, $sql_alter_phone);

if (@oci_execute($stmt_phone)) {
    echo "✅ تم إضافة عمود رقم الهاتف بنجاح.<br>";
} else {
    $e = oci_error($stmt_phone);
    if ($e['code'] == 1430) {
        echo "ℹ️ عمود رقم الهاتف موجود مسبقاً.<br>";
    } else {
        echo "❌ خطأ في إضافة عمود الهاتف: " . $e['message'] . "<br>";
    }
}

// 1.6 Create Product Images Table
$sql_create_images = "CREATE TABLE product_images (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    image_path VARCHAR2(255) NOT NULL
)";
$stmt_images = oci_parse($conn, $sql_create_images);
if (@oci_execute($stmt_images)) {
    echo "✅ تم إنشاء جدول صور المنتجات (product_images) بنجاح.<br>";
} else {
    $e = oci_error($stmt_images);
    if ($e['code'] == 955) { // ORA-00955: name is already used by an existing object
        echo "ℹ️ جدول صور المنتجات موجود مسبقاً.<br>";
    } else {
        echo "❌ خطأ في إنشاء جدول الصور: " . $e['message'] . "<br>";
    }
}

// 2. Add Admin User
$admin_user = "admin";
$admin_pass = "admin"; // You should hash this in production!

// Check if admin exists
$sql_check_admin = "SELECT count(*) FROM users WHERE username = :u";
$stmt_check = oci_parse($conn, $sql_check_admin);
oci_bind_by_name($stmt_check, ":u", $admin_user);
oci_define_by_name($stmt_check, "COUNT(*)", $count);
oci_execute($stmt_check);
oci_fetch($stmt_check);

if ($count == 0) {
    $sql_insert = "INSERT INTO users (username, password, email, role) VALUES (:u, :p, 'admin@store.com', 'admin')";
    $stmt_insert = oci_parse($conn, $sql_insert);
    oci_bind_by_name($stmt_insert, ":u", $admin_user);
    oci_bind_by_name($stmt_insert, ":p", $admin_pass);
    
    if (@oci_execute($stmt_insert)) {
        echo "✅ تم إنشاء حساب الأدمن (admin/admin).<br>";
    } else {
        $e = oci_error($stmt_insert);
        echo "❌ خطأ في إنشاء الأدمن: " . $e['message'] . "<br>";
    }
} else {
    echo "ℹ️ حساب الأدمن موجود مسبقاً.<br>";
}

echo "<br><a href='index.php'>العودة للصفحة الرئيسية</a>";
?>
